version: 2

updates:
  # GitHub Actions dependencies (grouped)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10
    groups:
      all-actions:
        patterns:
          - "*"

  # Python dependencies (grouped)
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10
    groups:
      backend-version-updates:
        patterns:
          - "*"
        applies-to: version-updates
      backend-security-updates:
        patterns:
          - "*"
        applies-to: security-updates

  - package-ecosystem: "pip"
    directory: "/src/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10
    groups:
      frontend-version-updates:
        patterns:
          - "*"
        applies-to: version-updates
      frontend-security-updates:
        patterns:
          - "*"
        applies-to: security-updates

  # npm dependencies (grouped)
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10
    groups:
      frontend-npm-version-updates:
        patterns:
          - "*"
        applies-to: version-updates
      frontend-npm-security-updates:
        patterns:
          - "*"
        applies-to: security-updates
